### ISSUE TITLE
Display more than 30 days of data in Grafana Dashboard

### ISSUE THREAD

**Issue by drthundermd** [jeremybz/waveplus_exporter#4]
Exporter works perfectly for me and I am able to get my data to display on the Grafana Dashboard application here:
[https://grafana.com/grafana/dashboards/12310-waveplus-sensor/](https://grafana.com/grafana/dashboards/12310-waveplus-sensor/
)

I have not been able to figure out how to get it to display more than 30 days of data. I tried adding --storage.tsdb.retention.time=1y to the prometheus command, but still only displays 30 days on the Grafana dashboard.
Full command being used:
`sudo prometheus --storage.tsdb.retention.time=1y --config.file ./agent-config.yml --web.listen-address=:9091 --web.enable-admin-api`

**Comment by jeremybz** [comment]
Hi! I think this is more a question about Grafana than the exporter or prometheus, but I'll try to help!
- Have you tried using the time selector in Grafana? That's generally on the top right and says something like "Last two days"

**Comment by jeremybz** [comment]
to check that you've got the data in prometheus, you can go to prometheus itself:
http://(IPADDRESS):9090/classic/graph?g0.range_input=1y&g0.expr=carbondioxide_ppm&g0.tab=0

**Comment by drthundermd** [comment]
I am all set, close ticketThanks!Sent from my iPhoneOn Oct 11, 2023, at 09:02, jeremybz ***@***.***> wrote:﻿
to check that you've got the data in prometheus, you can go to prometheus itself:
http://(IPADDRESS):9090/classic/graph?g0.range_input=1y&g0.expr=carbondioxide_ppm&g0.tab=0
